main: de.bypixels.thehunter.main.theHunterMain
name: theHunter
author: PixelsDE
version: 1.1.0
description: This is a big Minigame for Spigot and Bungeecord Server called TheHunter!

commands:
  start:
    description: Starts a Game!
  setlobby:
    description: Sets the Lobby!
  setspectator:
    description: Sets the Spawns of the EVENTSpectator!
  leave:
    description: Leave the Game!
    aliases: [l, lobby, hub, left, disconnect, quit]
  editmode:
    description: Enables and Disables the Editmode!
  setspawn:
    description: Sets the Player-Spawns!
  setarenacenter:
    description: Sets the Arenacenter!
  stats:
    descrption: Gives you infos about the Stats! 